export const CHANGE_SUPERMARKET_CONTENT = "CHANGE_SUPERMARKET_CONTENT" 
export const CHANGE_UNIVERSITY_CONTENT = "CHANGE_UNIVERSITY_CONTENT" 
export const CHANGE_CLASS_CONTENT = "CHANGE_CLASS_CONTENT"
