export const CHANGE_STUDY_PATH = "CHANGE_STUDY_PATH";
export const CHANGE_LESSONS_DIRECTION = "CHANGE_LESSONS_DIRECTION";
export const CHANGE_ALL_LESSONS = "CHANGE_ALL_LESSONS";
export const CHANGE_LIST_OFFSET = 'home/singers/CHANGE_LIST_OFFSET';
export const CHANGE_ENTER_LOADING = "CHANGE_ENTER_LOADING"; 
export const CHANGE_PULLUP_LOADING = 'PULLUP_LOADING';
export const CHANGE_PULLDOWN_LOADING = 'PULLDOWN_LOADING';