export const CHANGE_TITLE_CONTENT = "CHANGE_TITLE_CONTENT";
export const CHANGE_PERSON_ID = "CHANGE_PERSON_ID";
export const CHANGE_INTRODUCTION_CONTENT = "CHANGE_INTRODUCTION_CONTENT";
export const CHANGE_CATALOGUE_CONTENT = "CHANGE_CATALOGUE_CONTENT";
export const CHANGE_RECOMMEND_CONTENT = "CHANGE_RECOMMEND_CONTENT";
export const CHANGE_COMMENT_CONTENT = "CHANGE_COMMENT_CONTENT";
export const CHANGE_ORDER_TYPE = "CHANGE_ORDER_TYPE";
